name: NUnit Documentation Build Process

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the code
    - name: Lint Code Base
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: 'docs/**/*.md'      
  spellcheck: 
    name: "Spell check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the code
    - uses: actions/setup-node@v1
      name: Setup node
      with:
        node-version: '12'
    - run: npm install -g cspell
      name: Install cSpell
    - run: cspell --config ./cSpell.json "docs/**/*.md"
      name: run cSpell
  build_and_publish:
    name: "Build the site with docfx and publish"
    needs: [linting, spellcheck]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the code
    - uses: nunit/docfx-action@master
      name: Build with Docfx
      with:
        args: docs/docfx.json --warningsAsErrors true
    - name: Push to gh-pages branch (master only)
      if: ${{ github.ref == 'refs/heads/master'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
        publish_branch: gh-pages
  check_links:
    needs: [build_and_publish]
    runs-on: ubuntu-latest
    steps:
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
        directory: "./docs/_site"
